### ISSUE TITLE
FileHook function

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/HorkEyeTools#1]
I'm wondering do I have to find decode address of tlg for [this](https://github.com/Dir-A/ACV1FileHook/blob/d6b690d02f309b4d7240f4b6d7fc51a35597d08e/ACV1FileHook/ACV1FileHook/ACV1FileHook.cpp#L8) since VS pop "FileHook doesn't take 1 argument"
Well, I tried to trace with CreateFileW like in CMVS tutorial, but it only shows arcx.dat

**Comment by Dir-A** [comment]
https://github.com/Dir-A/ACV1FileHook/blob/d6b690d02f309b4d7240f4b6d7fc51a35597d08e/Example/HanaHime_cn/HanaHime_cn/HanaHime_cn.cpp#L40
Refer to this.
Readme out of version. I haven't had time to rewrite it yet.
Convert tlg to png after change the file extension to tlg

**Comment by Cosetto** [comment]
Should be fixed now in pull request
